% Adds all necessary folders as paths
addpath('ComparisonPlotScripts','NT1065scripts',genpath('SDRtracking'),...
    'EmailFunctions','HelpfulFunctions',genpath('L1'));%,genpath('GL'),...
    %genpath('L2'));